spring.application.name=wedding

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoints.web.base-path=/actuator